### ISSUE TITLE
mag 2 flux

### ISSUE THREAD

**Issue by yun201720** [temuller/piscola#1]
Hi,

I want to use piscola, I have light curves in magnitudes in AB system, but I do not know how to convert them to flux and then make a input file for piscola. What should I do?

**Comment by temuller** [comment]
Hey! Thanks for wanting to us piscola. 
I just want to warn you that it is not 100% finished. I am still testing a few aspects, but you are more than welcome to try it.
The first release version will be ready once the article I am currently working on is published (hopefully, I will finish it in the next few months)

Anyway, in the `data` directory you will find an example of input file. Basically, you need the photometry (flux, flux error and mjd), zero-points, magnitude system, Ra, Dec and redshift. The documentation is in [here](https://piscola.readthedocs.io/en/latest/), but it is still under development. 

To convert the magnitudes to flux you will need the zero-points, which will depend on the filters you are using. Which filters set are you using (e.g., SDSS, SNLS, etc.)?

Also, to install it, the best way is to clone the repo and run `python setup.py install`. I will repair the pip installation once I finish testing the code.

**Comment by yun201720** [comment]
Hey,

Thanks for the guiding.  
Piscola is an excellent work, l am looking forward to the coming article.

I have used the standard Bessell bandpasses (UBVRI) and PanSTARR (gri) bands, I just calibrated the instrument magnitudes to PanSTARR catalog. The UBVRI magnitudes are calibrated using transiform magnitudes of PanSTARR. Then, what should I do to convert these magnitudes to flux, and so that I can use piscola?  I have run the example successfully.

Thanks,

**Comment by temuller** [comment]
I recommend you work with the lightcurves in the natural system of each set of filters. If you check the `piscola/standards` directory, you will find a file called `magnitude_systems.txt` in which you will have the available magnitude systems pointing to the files used to define the natural systems of different filters sets. You can also modify this file to add other filters.

For Bessell bandpasses you probably want BD17 and for PanSTARR AB (the values used for these magnitude systems are taken from the Pantheon).

If you have the magnitudes, you should also have the zeropoints. Then, to convert magnitudes to flux you can either use the built-in function in piscola, `mag2flux()`, or do it yourself (mag = -2.5*np.log10(F) + ZP).

**Comment by yun201720** [comment]
Thank you so much. I will try to do these.
