### ISSUE TITLE
Add auto_download from SVO for creating new filters

### ISSUE THREAD

**Issue by emirkmo** [temuller/piscola#2]
Just a usability suggestions: Allow users to give SVO filter name (or instrument name) to auto create the right filter.

Using SVO python script automatically download the filter profile and use it, instead of having to manually add a filter. 

(I can make a PR for this later if you want).

**Comment by temuller** [comment]
This is a great idea! A PR sounds good or you can directly send me the script and I can modify it to implement it in PISCOLA. Note that I am curently working on the "mangling" branch.

**Comment by emirkmo** [comment]
I'll wait for the branch to be complete before adding the PR so as not to add complexity. I also made some PRs on a python wrapper for the SVO service:

see: https://github.com/hover2pi/svo_filters/pull/38
and https://github.com/hover2pi/svo_filters/pull/39

So now errors should properly surface and there shouldn't be an issue with improperly defined filter wavelengths which would break some of the calculations. 

I think using their python wrapper `svo_filters` would be great, although we could also use `astroquery`.

**Comment by temuller** [comment]
Using `svo_filters` sounds good. As you said, we can add it once the branch is complete.

**Comment by hover2pi** [comment]
I just uploaded v0.4.3 with these changes to PyPI. Feel free to pip install!

**Comment by temuller** [comment]
This feature will not be added. However, this tool exists: [SVO API](https://github.com/temuller/svo_api).
